---
  - name: install
    apt:
      name: nginx-full
      state: latest
      update_cache: yes
    notify:
      - start nginx
    tags: nginx

  - name: disable the default site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify:
      - restart nginx
    tags: nginx

  - name: create www directory
    file:
      path: "{{ www_dir }}"
      state: directory
      owner: deployer
      group: deployer
      mode: 0775
    tags: nginx

  - name: create configuration
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify:
      - restart nginx
    tags: nginx

  - name: create ssl directory
    template:
      path: "/etc/nginx/ssl/my_site"
      state: directory
      owner: deployer
      group: deployer
      mode: 0644
    tags: nginx

  - name: create sites enabled file
    template:
      src: my_site
      dest: /etc/nginx/sites-enabled/my_site
      owner: root
      group: root
      mode: 0655
    notify:
      - restart nginx
    tags: nginx

  - name: create ssl bundle srt
      template:
        src: ssl_bundle.crt
        dest: /etc/nginx/ssl/my_site/ssl_bundle.crt
        mode: 0644
      notify:
        - restart nginx
      tags: nginx

  - name: create ssl key
      template:
        src: my_site_ssl.key
        dest: /etc/nginx/ssl/my_site/my_site_ssl.key
        mode: 0644
      notify:
        - restart nginx
      tags: nginx

  - name: create host configuration
    template:
      src: "{{ server_type }}-host"
      dest: "/etc/nginx/sites-enabled/{{ server_name }}"
      mode: 0644
    notify:
      - restart nginx
    tags: nginx
