---
hostname: "application_name" #need set application name
timezone: "Europe/Kiev"
deployer_password: "$1$wm4RrCho$4pWGjyNTHJgPir6AkKNFv1"
ssh_keys:
  - "{{ lookup('file', 'keys/mistin.pub') }}"

# Nginx

server_name: "application_name" #set application name
www_dir: "/home/www/{{ server_name }}"

# PostgresSQL

postgresql:
  user: "deployer"
  password: "f62fee1b43f48bd0c1bf9b7d5b22f270" # deployer
  dbname: "application_name_production" #set database name
